<a href="https://colab.research.google.com/github/bob8dod/ML-studying/blob/main/Lab04_1(multi_variable_linear_regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import tensorflow as tf
import numpy as np


data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal([3,1], 0, 1))
b = tf.Variable(tf.random.normal([1], 0, 1))

learning_rate = 0.000001

def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 | 122733.1250
  100 |    16.7627
  200 |     1.6456
  300 |     1.6358
  400 |     1.6279
  500 |     1.6201
  600 |     1.6123
  700 |     1.6046
  800 |     1.5969
  900 |     1.5892
 1000 |     1.5815
 1100 |     1.5740
 1200 |     1.5664
 1300 |     1.5590
 1400 |     1.5515
 1500 |     1.5441
 1600 |     1.5367
 1700 |     1.5294
 1800 |     1.5220
 1900 |     1.5148
 2000 |     1.5075


In [35]:
W.numpy()

array([[1.2998202 ],
       [0.31058756],
       [0.39755067]], dtype=float32)

In [36]:
b.numpy()

array([0.49294022], dtype=float32)

In [39]:
Y #labels, 실제 값

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [40]:
#예측값 (hypothesis 이용)
predict(X).numpy()

array([[150.04312],
       [185.68013],
       [180.21996],
       [195.46832],
       [143.70714]], dtype=float32)

In [41]:
#새로운 데이터에 대한 예측
predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[182.25742],
       [172.0437 ]], dtype=float32)