<a href="https://colab.research.google.com/github/bob8dod/ML-studying/blob/main/ML_DL/08_DL_Model_(binary_classification_02).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Using Package
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
#Setting random seed
np.random.seed(3)
tf.random.set_seed(3)

In [ ]:
#Data Preprocessing
df = pd.read_csv("./dataset/pima-indians-diabetes.csv")
df.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   6       767 non-null    int64  
 1   148     767 non-null    int64  
 2   72      767 non-null    int64  
 3   35      767 non-null    int64  
 4   0       767 non-null    int64  
 5   33.6    767 non-null    float64
 6   0.627   767 non-null    float64
 7   50      767 non-null    int64  
 8   1       767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
#Classification of Data _ X,Y
data = df.values #Take value of data
X = data[:,0:8].astype('float64')
Y = data[:,8].astype('int64')
print(X,Y,sep='\n')

[[1.00e+00 8.50e+01 6.60e+01 ... 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 ... 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 ... 2.81e+01 1.67e-01 2.10e+01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.62e+01 2.45e-01 3.00e+01]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.01e+01 3.49e-01 4.70e+01]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.04e+01 3.15e-01 2.30e+01]]
[0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1
 0 1 0 1 1 0 1 0 0 1 0 1 1 0

In [ ]:
#Make model
model = Sequential()
model.add(Dense(64,input_dim=8,activation='relu'))
model.add(Dense(12,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
#Set Option
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#Operate Model, Evaluate Model
model.fit(X,Y,epochs=200,batch_size=10)
print('Accuracy: %.4f' %(model.evaluate(X,Y)[1]))

Epoch 1/200
77/77 [==============================] - 1s 879us/step - loss: 3.9561 - accuracy: 0.5664
Epoch 2/200
77/77 [==============================] - 0s 1ms/step - loss: 0.9358 - accuracy: 0.6380
Epoch 3/200
77/77 [==============================] - 0s 1ms/step - loss: 0.8860 - accuracy: 0.5994
Epoch 4/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7466 - accuracy: 0.6746
Epoch 5/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7077 - accuracy: 0.6717
Epoch 6/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7563 - accuracy: 0.6443
Epoch 7/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7334 - accuracy: 0.6856
Epoch 8/200
77/77 [==============================] - 0s 1ms/step - loss: 0.8478 - accuracy: 0.6505
Epoch 9/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7892 - accuracy: 0.6644
Epoch 10/200
77/77 [==============================] - 0s 1ms/step - loss: 0.6657 - accuracy: 0.6928
Epoch 1

77/77 [==============================] - 0s 1ms/step - loss: 0.4727 - accuracy: 0.7687
Epoch 83/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5245 - accuracy: 0.7296
Epoch 84/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5981 - accuracy: 0.7452
Epoch 85/200
77/77 [==============================] - 0s 1ms/step - loss: 0.4735 - accuracy: 0.7760
Epoch 86/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5329 - accuracy: 0.7335
Epoch 87/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5150 - accuracy: 0.7568
Epoch 88/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5052 - accuracy: 0.7772
Epoch 89/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5602 - accuracy: 0.7433
Epoch 90/200
77/77 [==============================] - 0s 1ms/step - loss: 0.4768 - accuracy: 0.7763
Epoch 91/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5175 - accuracy: 0.7559
Epoch 92/200


77/77 [==============================] - 0s 2ms/step - loss: 0.4010 - accuracy: 0.8105
Epoch 164/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4661 - accuracy: 0.7896
Epoch 165/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4117 - accuracy: 0.7959
Epoch 166/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4452 - accuracy: 0.8015
Epoch 167/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4132 - accuracy: 0.8113
Epoch 168/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4427 - accuracy: 0.7921
Epoch 169/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4332 - accuracy: 0.8061
Epoch 170/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4253 - accuracy: 0.7960
Epoch 171/200
77/77 [==============================] - 0s 4ms/step - loss: 0.3790 - accuracy: 0.8237
Epoch 172/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4579 - accuracy: 0.7715
Epoc