<a href="https://colab.research.google.com/github/bob8dod/ML-studying/blob/main/ML_DL/17_DL_Model_(NLP_Tokenizer%2C_pad_sequences%2C_Embedding).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences #for text padding(0)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense # NN: Flatten, Dense

import tensorflow as tf
import numpy as np

In [ ]:
#set seed
seed = 3
np.random.seed(seed)
tf.random.set_seed(seed)

In [ ]:
#Setting Data
docs = ["Its funny","great","well made movie",
        "want to recommand","wish see again",
        "dont know","not good","boring","worst of ever seen","shit" ]
label = np.array([1,1,1,1,1,0,0,0,0,0]) #for label, Y_train,,,

In [ ]:
#Data preprocessing
token = Tokenizer() #activate function
token.fit_on_texts(docs) #apply on docs
print(token.word_index) #check word_index

x=token.texts_to_sequences(docs) #Create a new array filled with only the index of the token
print(x)

x_padded = pad_sequences(x,4) #padding the text length for 4 _ input_length
print(x_padded)

word_size = len(token.word_index) + 1 #add 1 for 0 index(hidden)

{'its': 1, 'funny': 2, 'great': 3, 'well': 4, 'made': 5, 'movie': 6, 'want': 7, 'to': 8, 'recommand': 9, 'wish': 10, 'see': 11, 'again': 12, 'dont': 13, 'know': 14, 'not': 15, 'good': 16, 'boring': 17, 'worst': 18, 'of': 19, 'ever': 20, 'seen': 21, 'shit': 22}
[[1, 2], [3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14], [15, 16], [17], [18, 19, 20, 21], [22]]
[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 0  4  5  6]
 [ 0  7  8  9]
 [ 0 10 11 12]
 [ 0  0 13 14]
 [ 0  0 15 16]
 [ 0  0  0 17]
 [18 19 20 21]
 [ 0  0  0 22]]


In [ ]:
#Model Setting
model = Sequential()
model.add(Embedding(word_size,8,input_length=4)) #Embedding(input_dim, output_dim, input_length)
model.add(Flatten()) #Make 2D to 1D for NN
model.add(Dense(1,activation='sigmoid')) #output layer
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) #compiling

In [ ]:
#Model opperating
model.fit(x_padded,label,epochs=20) # fit(X,Y,epochs)
print('\nAccuracy: %.4f' %(model.evaluate(x_padded, label)[1]))

Epoch 1/20
1/1 [==============================] - 3s 3s/step - loss: 0.6893 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6868 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6845 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6821 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6797 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6773 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6749 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6725 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6701 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6678 - accuracy: 0.8000
Epoch 11/20
1/1 [=======================