<a href="https://colab.research.google.com/github/bob8dod/ML-studying/blob/main/2021ML/3.%20LogsiticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **iris데이터 LogisticRegression으로 학습하기**

In [ ]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
x = iris.drop('species', axis=1)
y = iris['species']

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
le = LabelEncoder()
y_le = le.fit_transform(y)
print(np.unique(y_le))

[0 1 2]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y_le,test_size=0.3,random_state=11,stratify=y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [ ]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
std.fit(x_train)
x_train_std = std.transform(x_train)
x_test_std = std.transform(x_test)

In [ ]:
x_train_std[:5,:]

array([[-0.54281112,  2.05673901, -1.17175955, -1.07027095],
       [-1.023783  ,  0.58930348, -1.3412289 , -1.33469084],
       [-1.74524081, -0.38898688, -1.3412289 , -1.33469084],
       [ 0.29888967, -0.63355947,  0.12750552,  0.11961852],
       [-0.18208221, -0.63355947,  0.40995444,  0.11961852]])

In [ ]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression(C=200, random_state=11) #L2, auto
logit.fit(x_train_std, y_train)

LogisticRegression(C=200, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_train_pred = logit.predict(x_train_std)
y_test_pred = logit.predict(x_test_std)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_train,y_train_pred)*100)
print(confusion_matrix(y_train,y_train_pred))

print(accuracy_score(y_test,y_test_pred)*100)
print(confusion_matrix(y_test,y_test_pred))

98.09523809523809
[[35  0  0]
 [ 0 34  1]
 [ 0  1 34]]
100.0
[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


# **LogisticRegression "regularization값"에 따른 정확도 측정**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
wine = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data', names=['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline'])
#wine.columns = ['class label','alchohol',,,]
wine.head()

class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

In [ ]:
x = wine.drop('class label', axis=1)
y = wine['class label']
#x, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
print(x.head())
print('-----------------------------')
print(y.head())
print(np.unique(y))

   alchohol  malic acid   ash  ...   hue  OD208  proline
0     14.23        1.71  2.43  ...  1.04   3.92     1065
1     13.20        1.78  2.14  ...  1.05   3.40     1050
2     13.16        2.36  2.67  ...  1.03   3.17     1185
3     14.37        1.95  2.50  ...  0.86   3.45     1480
4     13.24        2.59  2.87  ...  1.04   2.93      735

[5 rows x 13 columns]
-----------------------------
0    1
1    1
2    1
3    1
4    1
Name: class label, dtype: int64
[1 2 3]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=11,stratify=y)

In [ ]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
std.fit(x_train)
x_train_std = std.transform(x_train)
x_test_std = std.transform(x_test)
print(x_train_std[:5,])
print('-----------------------------')
print(x_test_std[:5,])

[[-1.19559007  0.90215966 -1.36350298 -0.1231367  -0.92476899 -0.52780615
  -0.41948853  0.17676169  0.47356473 -1.69888925 -0.14320198  0.56044389
  -0.6101467 ]
 [ 0.62060635 -0.49889045  0.21879539  0.31478733  0.04323595  0.58633718
   0.89589577 -0.71621219  0.45609314  0.05151285  0.34806438  1.13865146
   0.53741053]
 [ 0.09292766  1.27404333 -0.1285384   0.89868605 -1.07369282 -1.08487781
  -0.46857003  2.12506835  0.03677489 -0.08595329 -0.54514718 -0.87130818
  -0.76809699]
 [ 0.27700162 -0.52483583 -0.82320598 -2.40034169  0.04323595  0.50675551
   0.67993715 -0.71621219 -0.5572593  -0.27840587  0.39272495  1.04228353
   0.95646233]
 [-0.83971374  0.38325221 -0.51446483 -0.41508606 -0.85030707  0.18842885
   0.17930582 -0.79739164  0.68322386 -1.30023747  0.83933073  0.90461506
  -1.49337895]]
-----------------------------
[[ 1.41826019  1.48160631  1.49235261  1.48258476 -0.25461172 -0.44822448
  -1.28332299  1.71917113 -0.43495815  1.93021667 -1.57234048 -1.4357489
  -0.62

In [ ]:
from sklearn.linear_model import LogisticRegression
lr_2_10 = LogisticRegression(penalty='l2', C=10.0, solver='saga') # L2 with C(=1/λ)=10
lr_2_1 = LogisticRegression(penalty='l2', C=1.0, solver='saga') # L2 with C(=1/λ)=1
lr_2_0_1 = LogisticRegression(penalty='l2', C=0.1, solver='saga') # L2 with C(=1/λ)=0.1
lr_1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga') # L1 with C(=1/λ)=10
lr_1_1 = LogisticRegression(penalty='l1', C=1.0, solver='saga') # L1 with C(=1/λ)=1
lr_1_0_1 = LogisticRegression(penalty='l1', C=0.1, solver='saga') # L1 with C(=1/λ)=0.1

In [ ]:
lr_2_10.get_params().keys()

dict_keys(['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])

In [ ]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
#lr.score()사용
lr_2_10.fit(x_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr_2_10.score(x_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr_2_10.score(x_test_std, y_test))

lr_2_1.fit(x_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr_2_1.score(x_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr_2_1.score(x_test_std, y_test))

lr_2_0_1.fit(x_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr_2_0_1.score(x_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr_2_0_1.score(x_test_std, y_test))

lr_1_10.fit(x_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr_1_10.score(x_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr_1_10.score(x_test_std, y_test))

lr_1_1.fit(x_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr_1_1.score(x_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr_1_1.score(x_test_std, y_test))

lr_1_0_1.fit(x_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr_1_0_1.score(x_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr_1_0_1.score(x_test_std, y_test))


Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9629629629629629
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9629629629629629
Training accuracy with L2 and λ=10: 0.9919354838709677
Test accuracy with L2 and λ=10: 0.9814814814814815
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9629629629629629
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9629629629629629
Training accuracy with L1 and λ=10: 0.967741935483871
Test accuracy with L1 and λ=10: 0.9444444444444444


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [ ]:
# # L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
# print(lr2_10.intercept_)
# print(lr2_1.intercept_)
# print(lr2_0_1.intercept_)

# print(lr2_10.coef_)
# print(lr2_1.coef_)
# print(lr2_0_1.coef_)

# # L1 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
# print(lr1_10.intercept_)
# print(lr1_1.intercept_)
# print(lr1_0_1.intercept_)

# print(lr1_10.coef_)
# print(lr1_1.coef_)
# print(lr1_0_1.coef_)

NameError: ignored